/**
 * Icons Configuration - Nano Banana Admin Panel
 * 
 * This file centralizes all icon imports from lucide-react.
 * Import icons from this file throughout the application for consistency.
 */

import {
  Users,
  User,
  FolderTree,
  Image,
  CreditCard,
  UserCheck,
  MessageSquare,
  Settings,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  LogOut,
  Bell,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Check,
  AlertCircle,
  Info,
  Home,
  BarChart3,
  FileText,
  Download,
  Upload,
  Filter,
  Calendar,
  Clock,
  Mail,
  Phone,
  MapPin,
  Globe,
  Link as LinkIcon,
  Copy,
  Share2,
  Save,
  RefreshCw,
  MoreVertical,
  MoreHorizontal,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronDown,
  ChevronUp,
  CornerDownRight,
  Star,
  Bookmark,
  Code,
  TrendingUp,
  Shield,
  Smartphone
} from 'lucide-react';

// Export all icons
export const Icons = {
  // Sidebar Menu Icons
  users: Users,
  user: User,
  categories: FolderTree,
  images: Image,
  subscriptionPlan: CreditCard,
  userSubscription: UserCheck,
  feedback: MessageSquare,
  appSettings: Settings,
  
  // Navigation Icons
  menu: Menu,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  cornerDownRight: CornerDownRight,
  
  // Action Icons
  logout: LogOut,
  bell: Bell,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  save: Save,
  refresh: RefreshCw,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  
  // Status Icons
  alert: AlertCircle,
  info: Info,
  star: Star,
  bookmark: Bookmark,
  trending: TrendingUp,
  x: X,
  
  // General Icons
  home: Home,
  chart: BarChart3,
  file: FileText,
  fileText: FileText,
  download: Download,
  upload: Upload,
  filter: Filter,
  calendar: Calendar,
  clock: Clock,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  globe: Globe,
  link: LinkIcon,
  copy: Copy,
  share: Share2,
  code: Code,
  shield: Shield,
  smartphone: Smartphone,
};

// Export individual icons for direct import
export {
  Users,
  User,
  FolderTree,
  Image,
  CreditCard,
  UserCheck,
  MessageSquare,
  Settings,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  LogOut,
  Bell,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Check,
  AlertCircle,
  Info,
  Home,
  BarChart3,
  FileText,
  Download,
  Upload,
  Filter,
  Calendar,
  Clock,
  Mail,
  Phone,
  MapPin,
  Globe,
  LinkIcon,
  Copy,
  Share2,
  Save,
  RefreshCw,
  MoreVertical,
  MoreHorizontal,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronDown,
  ChevronUp,
  CornerDownRight,
  Star,
  Bookmark,
  Code,
  TrendingUp,
  Shield,
  Smartphone
};

export default Icons;
